# file: group_vars/osx.yml

---
ruby:
  version: 2.1.3p242

# executables -------------------------------------------------------------
executables:
  brew: /usr/local/bin/brew
  vim: /Applications/MacVim.app/Contents/MacOS/Vim
  zsh: /usr/local/bin/zsh

# directories -------------------------------------------------------------
directories:
  etc: /usr/local/etc
  var: /usr/local/var
# auth --------------------------------------------------------------------
vwall:
  user:
    name: vwall
    group: staff
    shell: "{{ executables.zsh }}"
  home: /Users/vwall
zsh:
  theme:
    dir: ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/themes
