# file: group_vars/dotfiles.yml

---
dotfiles:
  vwall:
    git:
      repos:
        - name: antigen
          repo: "git://github.com/zsh-users/antigen.git"
          dest: "{{ vwall.home }}/.antigen"
