---
- name: Git Repos
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items: "{{ dotfiles.vwall.git.repos }}"

- name: copy dotfiles
  copy: src={{ item }} dest={{vwall.home}}/.{{ item | basename }}
  with_fileglob:
    - ./*
